version: '3.3'

networks:
  whatdoyouthink-api:
    external: true

services:
  app:
    container_name: whatdoyouthink-api
    image: node:12-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    networks:
      - whatdoyouthink-api
    command: "npm start"

  mongo:
    container_name: whatdoyouthink-api-mongo
    image: mongo:4.2
    volumes:
      - ~/.mongo/whatdoyouthink-api:/data/db
    ports:
      - "4001:27017"
    networks:
      - whatdoyouthink-api